/**
 * @file ChatDTO.ts
 * @description Data Transfer Objects for the Chat module.
 */

/**
 * Request payload for sending a message from the widget.
 * Standardized structure for all incoming public chat messages.
 */
export interface ChatMessageRequestDTO {
  /**
   * The content of the message sent by the user.
   */
  message: string;
  /**
   * The unique identifier (UUID) of the tenant owning the widget.
   */
  tenantId: string;
}

/**
 * The core data returned in a chat message response.
 * This is wrapped by the standard ApiResponse structure.
 */
export interface ChatMessageResponseDTO {
  /**
   * The text response generated by the AI.
   */
  response: string;
  /**
   * Optional trace or log information for debugging internal tool calls.
   */
  trace?: Array<Record<string, unknown>>;
  /**
   * ISO timestamp of when the response was generated.
   */
  timestamp: string;
}
