/**
 * @file ChatService.ts
 * @description High-level orchestrator for AI chat interactions.
 * This service manages the lifecycle of a text-to-text session using the Gemini
 * Multimodal Live API, handling prompt submission, text streaming, and recursive tool calls.
 *
 * @module Services/AI/ChatService
 * @category AI
 */

import WebSocket from "ws";
import { GeminiService } from "./GeminiService";
import { ToolDispatcher } from "./ToolDispatcher";
import { tools as toolDefinitions } from "../../config/tools";
import { GeminiFunctionCall, ToolDeclaration } from "../../types/gemini";

/**
 * Structured response for single-turn or simulated multi-turn chat calls.
 */
export interface ChatResponse {
  /** The final aggregated text response from the model. */
  response: string;
  /**
   * Execution trace detailing tool calls and their results.
   * Essential for debugging AI behavior and providing transparency in the UI.
   */
  trace: {
    /** Element type: 'tool_call' or 'tool_response' */
    type: string;
    /** The name of the function invoked. */
    name: string;
    /** The arguments generated by the model for this call. */
    args?: unknown;
    /** The resulting data returned from the backend service. */
    result?: unknown;
  }[];
}

/**
 * Service responsible for high-level AI conversation management.
 * Acts as a bridge between the raw WebSocket-based GeminiService and the application logic.
 */
export class ChatService {
  /**
   * Creates an instance of ChatService.
   * @param toolDispatcher - The dispatcher used to resolve and execute model-generated function calls.
   */
  constructor(private toolDispatcher: ToolDispatcher) {}

  /**
   * Orchestrates a conversation with Gemini by establishing a temporary session,
   * handling multi-turn tool loops, and aggregating fragments into a final response.
   *
   * @param prompt - The user's input string or instructions.
   * @param systemInstruction - The systemic persona constraints for the AI.
   * @returns A promise resolving to the final text and a complete tool execution trace.
   * @throws Error if the connection times out or the max tool recursion limit is hit.
   */
  public async getAiResponse(
    prompt: string,
    systemInstruction: string,
  ): Promise<ChatResponse> {
    /** Collection of all tool-related events occurring during this request. */
    const trace: {
      type: string;
      name: string;
      args?: unknown;
      result?: unknown;
    }[] = [];

    /** Track current depth of model-requested tool chains to prevent infinite loops. */
    let turnCount = 0;
    const MAX_TURNS = 10;

    /** Default runtime settings for the temporary Gemini session. */
    const settings = {
      voiceName: "Aoede",
      systemInstruction,
      temperature: 0.7,
    };

    /** Instantiate a transient GeminiService for this request/response lifecycle. */
    const gemini = new GeminiService(toolDefinitions as ToolDeclaration[]);
    let activeWs: WebSocket | null = null;

    return new Promise((resolve, reject) => {
      let finalResponse = "";

      /** Safety timeout to prevent requests from hanging indefinitely. */
      const timeout = setTimeout(() => {
        if (activeWs && activeWs.readyState === WebSocket.OPEN) {
          activeWs.close();
        }
        reject(new Error("AI response timed out"));
      }, 20000);

      gemini
        .connectToGemini(
          async (response) => {
            /** Handle incoming text fragments from the model. */
            if (response.serverContent?.modelTurn) {
              const parts = response.serverContent.modelTurn.parts || [];
              for (const p of parts) {
                if (p.text) finalResponse += p.text;
              }
            }

            /**
             * Tool Interaction Logic:
             * If the model requests function calls, execute them and return results.
             * This triggers another model turn.
             */
            if (response.toolCall && activeWs) {
              turnCount++;

              /** Enforce recursion safety. */
              if (turnCount > MAX_TURNS) {
                if (activeWs.readyState === WebSocket.OPEN) activeWs.close();
                return reject(new Error("Maximum tool turns exceeded"));
              }

              const functionCalls = response.toolCall.functionCalls;
              const toolResponses: {
                id?: string;
                response: { result: unknown };
              }[] = [];

              for (const call of functionCalls) {
                // 1. Record the intent in the trace
                trace.push({
                  type: "tool_call",
                  name: call.name,
                  args: call.args,
                });

                // 2. Dispatch the call to the actual backend logic
                const toolResult = await this.toolDispatcher.dispatch(
                  call as GeminiFunctionCall,
                );

                // 3. Record the result in the trace
                trace.push({
                  type: "tool_response",
                  name: call.name,
                  result: toolResult,
                });

                // 4. Queue for the API tool_response payload
                toolResponses.push({
                  id: call.id,
                  response: { result: toolResult },
                });
              }

              /** Send the aggregated batch of results back to the AI. */
              gemini.sendToolResponse(activeWs, toolResponses);
            }
          },
          () => {
            /** Cleanup and resolve once the model naturally closes the session. */
            clearTimeout(timeout);
            resolve({ response: finalResponse, trace });
          },
          settings,
        )
        .then((ws) => {
          activeWs = ws;
          /** Kick off the conversation with the user's initial prompt. */
          gemini.sendText(ws, prompt);

          /**
           * Session Lifecycle Management:
           * Monitoring for inactivity or completion to avoid orphaned WebSockets.
           */
          const checkDone = setInterval(() => {
            if (finalResponse.length > 0) {
              clearInterval(checkDone);
              /**
               * Grace period for trailing audio/text fragments and multi-turn tool loops.
               * Increased to 7 seconds to prevent premature disconnection.
               */
              setTimeout(() => {
                if (ws.readyState === WebSocket.OPEN) ws.close();
              }, 7000);
            }
          }, 1000);

          /**
           * Hard cutoff for the entire session.
           * Increased to 30 seconds to allow for complex reasoning and multiple tool calls.
           */
          setTimeout(() => {
            clearInterval(checkDone);
            if (ws.readyState === WebSocket.OPEN) ws.close();
          }, 30000);
        })
        .catch((err) => {
          clearTimeout(timeout);
          reject(err);
        });
    });
  }
}
