/**
 * @file gemini.ts
 * @description Type definitions for the Gemini Multimodal Live API.
 * This file defines the structures for bidirectional communication with Google's
 * Generative AI models, specifically focusing on multimodal session events and tool usage.
 *
 * @module Types/Gemini
 * @category AI
 */

/**
 * Represents a single function call generated by the AI model.
 */
export interface GeminiFunctionCall {
  /** Optional unique identifier for the specific call instance, used for matching responses. */
  id?: string;
  /** The name of the registered tool/function to be executed. */
  name: string;
  /** Key-value pairs of arguments extracted by the model to be passed to the function. */
  args: Record<string, unknown>;
}

/**
 * Payload structure for returning results of tool executions back to the model.
 * Required for the model to continue its reasoning after a function call.
 */
export interface GeminiToolResponse {
  /** Collection of results from one or more function executions. */
  functionResponses: {
    /** The actual data generated by the backend service. */
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    response: Record<string, any>;
    /** Must match the ID from the original tool call to ensure correct mapping. */
    id?: string;
  }[];
}

/**
 * Universal response structure for incoming messages from the Gemini WebSocket.
 */
export interface GeminiResponse {
  /** Contains model-generated media or state updates. */
  serverContent?: {
    /** Represents the AI's "turn" in the conversation. */
    modelTurn?: {
      /** Individual content fragments (text, audio, or tool calls). */
      parts?: {
        /** Plain text generated by the model. */
        text?: string;
        /** Multimodal data (typically base64 audio chunks). */
        inlineData?: {
          /** The encoding format, e.g., 'audio/pcm'. */
          mimeType: string;
          /** Base64 encoded media payload. */
          data: string;
        };
        /** A request for the client/server to execute a local function. */
        call?: GeminiFunctionCall;
      }[];
    };
  };
  /** Explicit tool call wrapper used in certain API notification flows. */
  toolCall?: {
    /** Array of one or more functions the model requested to run simultaneously. */
    functionCalls: GeminiFunctionCall[];
  };
  /** Handshake flag indicating the session configuration (setup) was successful. */
  setupComplete?: boolean;
}

/**
 * Schema for defining local capabilities to the AI model during session setup.
 */
export interface ToolDeclaration {
  /** List of functions that the AI is authorized to invoke during this session. */
  functionDeclarations: {
    /** Unique identifier for the tool. */
    name: string;
    /** Detailed description used by the model to understand when and how to use the tool. */
    description: string;
    /** JSON Schema defining the input structure expected by the tool. */
    parameters: {
      /** The root data type, usually 'object'. */
      type: string;
      /** Map of field names to their JSON Schema constraints. */
      properties: Record<string, unknown>;
      /** List of property names that the AI must provide in every call. */
      required: string[];
    };
  }[];
}
